#!/bin/sh

set -e

[ 3 != $# ] && {
	echo "needs more foooood...";
	echo "usage: $0 <bridge> <name> <addr>";
	exit 1; }

bridge=$1
name=$2
peername=${name}peer
addr=$3

if ip netns list | grep -q $name; then
	pids=$(ip netns pids $name)
	if [ ! -z "$pids" ]; then
		echo "netns $name have processes:"
		for p in $pids; do ps --pid $p -o pid,ppid,start,ruser,command; done
		exit 2
	fi
else
	ip netns add $name
fi

# In case of resume, let's ensure that the device exists in given ns
if ip link show $peername > /dev/null 2>&1; then
	ip netns exec $name ip link show $name > /dev/null 2>&1 || {
		echo "missing dev in netns $name, manual cleanup"; exit 3; }
else
	ip link add name $name type veth peer name $peername
	ip link set dev $name netns $name
fi
ip netns exec $name ifconfig lo 127.0.0.1 up
ip netns exec $name ifconfig $name $addr up

ifconfig $peername up

brctl show | grep -qP "^$bridge\s" || brctl addbr $bridge
brctl show | grep -qP "\s$peername\$" || brctl addif $bridge $peername
