#!/bin/sh

# Original version by Rob Landley of http://landley.net

set -e

[ $# -lt 2 ] && { echo "usage: $0 <dest> targets ..."; exit 1; }

mkchroot() {
  dest=$1
  shift

  [ ! -d "$dest" ] && { echo "error: dir '$dest' does not exists"; exit 1; }

  for i in "$@"
  do
    echo $i | grep -qP '^\.?/' || i=$(readlink -f "$i")

    # Skip if target already exist
    [ -e "$dest/$i" ] && continue

    if [  ! -e "$i" ]
    then
      echo "error: not found: $i"
      exit 1
    else
      echo "$i -> $dest/$i"

      # @todo find way to copy block devices, might be good to leave
      # this to the caller
      mkdir -p "$dest/$(dirname $i)"
      cp -Lr "$i" "$dest/$i"

      # Recursively copy shared libraries'
      if [ -x "$i" ] && [ -f "$i" ]
      then
        mkchroot "$dest" $(ldd "$i" | grep -o '/.* ')
      fi
    fi
  done
}

mkchroot "$@"
